# Generated by Django 3.1.2 on 2020-10-15 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='subject', to='courses.Course'),
        ),
    ]
