# Generated by Django 3.1.2 on 2020-10-20 21:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20201015_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.SlugField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Only lowercase alphanumeric, dashes, and underscores allowed', regex='^[a-z0-9_\\-]+$')])),
            ],
        ),
        migrations.RemoveField(
            model_name='guide',
            name='teacher',
        ),
        migrations.AddField(
            model_name='guide',
            name='tags',
            field=models.ManyToManyField(null=True, to='courses.Tag'),
        ),
    ]
