# Generated by Django 3.0.6 on 2020-10-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20201020_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='tags',
            field=models.ManyToManyField(to='courses.Tag'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='courses',
            field=models.ManyToManyField(related_name='subject', to='courses.Course'),
        ),
    ]
