# Generated by Django 3.0.6 on 2020-10-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20201027_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='tags',
            field=models.ManyToManyField(related_name='guide', to='courses.Tag'),
        ),
    ]
