# Generated by Django 3.1.2 on 2020-11-04 20:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20201027_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='url',
            field=models.SlugField(max_length=100, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Only lowercase alphanumeric, dashes, and underscores allowed', regex='^[a-z0-9_\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
