# Generated by Django 3.0.6 on 2021-01-16 03:49

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20201104_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['url']},
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('guide', models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='guides')),
                ('course', models.ManyToManyField(related_name='proposed_course', to='courses.Course')),
                ('tags', models.ManyToManyField(related_name='proposed_tags', to='courses.Tag')),
            ],
        ),
    ]
